---
fail_fast: true
exclude: "helm-charts/.*/templates/.*"
default_stages: [push]
default_language_version:
  python: python3.9
default_install_hook_types: [pre-push]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: requirements-txt-fixer
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0
  hooks:
  - id: terraform_fmt
    name: terraform format
  #TODO Enable - id: terraform_docs
...
