---
replicaCount: 1

image:
  repository: czm41k/python-http-weather
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

configMap:
  url: "https://api.openweathermap.org/data/2.5/weather"
  city: "2643743"
  token: "a6311858fb35df63b55216bae4aa952a"
...
