---
name: Deploy app with helm
on:
  workflow_run:
    workflows: ["Build and upload artifact"]
    types: ["completed"]
  workflow_dispatch:
env:
  AWS_REGION: "us-west-1"
  BUCKET_NAME: "czm41k-terraform-state"
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Generate kubeconfig with aws-cli
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name czm41k-eks-dev
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Check kubeconfig works
      run: kubectl get ns
    - name: install helm3
      uses: azure/setup-helm@v3
      with:
        version: '3.9.4'
    - name: check helm
      run: helm ls
    - name: install app with helm --dry-run
      working-directory: helm-charts/python-webserver/
      run: helm upgrade python-webserver . --install --wait --atomic --namespace=app --values=./values.yaml --dry-run
    - name: Approve before deploy
      uses: trstringer/manual-approval@main
      with:
        secret: ${{ github.TOKEN }}
        approvers: czm41k
    - name: install app with helm
      working-directory: helm-charts/python-webserver/
      run: helm upgrade python-webserver . --install --wait --atomic --create-namespace --namespace=app --timeout=2m --values=./values.yaml
...
