---
name: '2-App: Check, build and upload artifact'
on:
  push:
    tags: [ "v[0-9].[0-9]+.[0-9]" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out main
        uses: actions/checkout@main
      - name: Install pylint
        run: pip3 install pylint==2.15.2
      - name: Run linter
        run: pylint $GITHUB_WORKSPACE/app-code/app.py

  scan-bandit:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out main
        uses: actions/checkout@main
      - name: Install bandit
        run: pip3 install bandit==1.7.4
      - name: Run scanner
        run: bandit -r app-code/

  build:
    needs: [lint,scan-bandit]
    name: "Build and upload to registry"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        varFilePath: ./.github/variables/dev-vars.env
    - name: Generate REPO envvar
      run: echo "REPO=617686195573.dkr.ecr.us-west-1.amazonaws.com/${{ env.OWNER }}-${{ env.APP_NAME }}-${{ env.ENVR }}" >> $GITHUB_ENV
    - name: Set tag
      id: set-tag
      env:
        MANUAL_TAG: ${{inputs.tag }}
      run: |
        if [[ $MANUAL_TAG ]]
        then
          TAG=${{ inputs.tag }}
        else
          TAG=${GITHUB_REF_NAME}
        fi
        echo "TAG is ${TAG}"
        echo "Putting TAG to GITHUB_ENV"
        echo "TAG=${TAG}" >> $GITHUB_ENV
        echo "Putting tag for job output (to pass to deploy) as well"
        echo "::set-output name=TAG::${TAG}"
    - name: Build the Docker image
      run: docker build app-code/ --file app-code/Dockerfile --tag ${{ env.REPO }}:${{ env.TAG }}
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Docker login
      run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.REPO }}
    - name: Upload to Registry
      run: docker push ${{ env.REPO }}:${{ env.TAG }}
    outputs:
      TAG: ${{ steps.set-tag.outputs.TAG }}
...
