---
name: Deploy app with helm
on:
  workflow_run:
    workflows: ["Build image"]
    types: ["completed"]
  workflow_dispatch:
env:
  AWS_REGION: "us-west-1"
  BUCKET_NAME: "czm41k-terraform-state"
jobs:
  kubeconfig:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Generate kubeconfig with aws-cli
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name czm41k-eks-dev
    - name: cat kubeconfig
      id: kubeconfig
      run: |
        cat /home/runner/.kube/config
        echo "::set-output name=kubeconfig::$(cat /home/runner/.kube/config)"
    outputs:
      kubeconfig: ${{ steps.kubeconfig.output }}

  helm-deployment:
    needs: [kubeconfig]
    runs-on: 'ubuntu-latest'
    steps:
    # - name: Wait for manual approval
    #   uses: trstringer/manual-approval@main
    #   with:
    #     secret: ${{ github.TOKEN }}
    #     approvers: czm41k
    - uses: actions/checkout@v1
    - name: 'Show kubeconfig'
      run: |
        echo "Passed kubeconfig is" ${{needs.kubeconfig.outputs.kubeconfig}}
        echo ${{needs.kubeconfig.outputs.kubeconfig}}
  #     uses: 'deliverybot/helm@main'
  #     with:
  #       release: 'python-webserver'
  #       namespace: 'app'
  #       chart: 'app'
  #       token: '${{ github.token }}'
  #       values: |
  #         name: foobar
  #     env:
  #       KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
  # https://github.com/marketplace/actions/helm-deploy
...
