
---
name: Build and upload artifact

on:
  push:
    tags: [ "v[0-9].[0-9]+.[0-9]" ]
    paths:
      - 'app-code/**'
      - '.github/workflows/app-*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Image tag'
        required: true
        type: string

env:
  REPO: "617686195573.dkr.ecr.us-west-1.amazonaws.com/czm41k-ecr-dev"
  IMAGE_NAME: weather-checker
  AWS_REGION: us-west-1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: print manual tags
      if: ${{ inputs.print_tags }}
      run: echo  The tags are ${{ inputs.tags }}
    - name: Set tag
      env:
        MANUAL_TAG: ${{inputs.tags }}
      run: |
        if [[ $MANUAL_TAG ]]
        then
          echo "TAG=${{ inputs.tags }}" >> $GITHUB_ENV
        else
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        fi
    - name: Build the Docker image
      run: docker build app-code/ --file app-code/Dockerfile --tag ${{env.REPO}}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Upload to Registry
      run: docker push ${{ env.REPO }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
...
