---
name: '4-Destroy all infra'
on:
  workflow_dispatch:
    inputs:
      delete_remote:
        description: 'Destroy s3-bucket & dynamodb lock anyway'
        required: true
        type: boolean
        default: false
      tool:
        description: "Which tool to use: terraform or terragrunt"
        required: true
        default: "terragrunt"
        type: string

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  delete-app-release:
    name: "Delete app with helm"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        varFilePath: ./.github/variables/dev-vars.env
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Generate kubeconfig with aws-cli
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name "${{ env.OWNER }}-eks-${{ env.ENVR }}"
    - name: install helm3
      uses: azure/setup-helm@v3
      with:
        version: ${{ env.helm_version }}
    - name: delete app with helm
      working-directory: "helm-charts/${{ env.APP_NAME }}/"
      run: helm uninstall ${{ env.APP_NAME }} --wait --namespace=app --timeout=5m

  terragrunt-destroy:
    needs: [delete-app-release]
    if: ${{ inputs.tool == 'terragrunt' && always() }}
    name: "Destroy with Terragrunt"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terragrunt/dev/eks-infra/
        shell: bash
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        varFilePath: ./.github/variables/dev-vars.env
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: ${{ env.terragrunt_version }}
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Terragrunt Init
      run: terragrunt init
    - name: Approve before Destroy
      uses: trstringer/manual-approval@main
      with:
        secret: ${{ github.TOKEN }}
        approvers: ${{ env.OWNER }}
    - name: Terragrunt destroy with mounted kubeconfig
      # https://archive.sweetops.com/terraform/2021/07/
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_DEFAULT_REGION }} --name "${{ env.OWNER }}-eks-${{ env.ENVR }}" || true
        terragrunt destroy --auto-approve=true
      continue-on-error: true

  terraform-destroy:
    if: ${{ inputs.tool == 'terraform' && always() }}
    needs: [delete-app-release]
    name: "Destroy with Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/dev/
        shell: bash
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        varFilePath: ./.github/variables/dev-vars.env
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Terraform Init
      run: terraform init
    - name: Approve before Destroy
      uses: trstringer/manual-approval@main
      with:
        secret: ${{ github.TOKEN }}
        approvers: ${{ env.OWNER }}
    - name: Terraform destroy with mounted kubeconfig
      # https://archive.sweetops.com/terraform/2021/07/
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_DEFAULT_REGION }} --name "${{ env.OWNER }}-eks-${{ env.ENVR }}" || true
        terraform destroy --auto-approve=true
      continue-on-error: true

  delete-remote-state:
    if: ${{ always() && inputs.delete_remote }}
    needs: [delete-app-release, terraform-destroy, terragrunt-destroy]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        varFilePath: ./.github/variables/dev-vars.env
    - name: Generate BUCKET_NAME envvar
      run: |
        if [[ ${{inputs.tool }} -eq 'terraform' ]]
        then
          BUCKET_NAME="${{env.OWNER}}-${{ inputs.tool }}-${{env.ENVR}}-state"
        else
          BUCKET_NAME="${{env.OWNER}}-${{ inputs.tool }}-state"
        fi
        echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV
        echo "BUCKET_NAME is ${BUCKET_NAME}"
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Delete dynamodb table
      run: aws dynamodb delete-table --table-name "${{ env.BUCKET_NAME }}-lock"
      continue-on-error: true
    - name: Delete S3 bucket
      run: aws s3 rb s3://${{ env.BUCKET_NAME }} --force
...
