---
name: '4-Destroy all infra'
on:
  workflow_dispatch:
    inputs:
      delete_remote:
        description: 'Destroy s3-bucket & dynamodb lock anyway'
        required: true
        type: boolean
        default: false
      tool:
        description: "Which tool to use: terraform or terragrunt"
        required: true
        default: "terragrunt"
        type: string

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  terragrunt-destroy:
    if: ${{ inputs.tool == 'terragrunt' }}
    name: "Destroy with Terragrunt"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terragrunt/dev/eks-infra/
        shell: bash
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        varFilePath: ./.github/variables/dev-vars.env
    - name: Generate BUCKET_NAME envvar
      run: echo "BUCKET_NAME=${{env.OWNER}}-terraform-${{env.ENVR}}-state" >> $GITHUB_ENV
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: ${{ env.terragrunt_version }}
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Terragrunt Init
      run: terragrunt init
    - name: Approve before Destroy
      uses: trstringer/manual-approval@main
      with:
        secret: ${{ github.TOKEN }}
        approvers: ${{ env.OWNER }}
    - name: Terragrunt destroy with mounted kubeconfig
      # https://archive.sweetops.com/terraform/2021/07/
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_DEFAULT_REGION }} --name "${{ env.OWNER }}-eks-${{ env.ENVR }}"
        terragrunt destroy --auto-approve=true
      continue-on-error: true

  terraform-destroy:
    if: ${{ inputs.tool == 'terraform' }}
    name: "Destroy with Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/dev/
        shell: bash
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        varFilePath: ./.github/variables/dev-vars.env
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Terraform Init
      run: terraform init
    - name: Approve before Destroy
      uses: trstringer/manual-approval@main
      with:
        secret: ${{ github.TOKEN }}
        approvers: ${{ env.OWNER }}
    - name: Terraform destroy with mounted kubeconfig
      # https://archive.sweetops.com/terraform/2021/07/
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_DEFAULT_REGION }} --name "${{ env.OWNER }}-eks-${{ env.ENVR }}"
        terraform destroy --auto-approve=true
      continue-on-error: true

  delete-remote-state:
    if: ${{ always() && inputs.delete_remote }}
    needs: [terraform-destroy, terragrunt-destroy]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        varFilePath: ./.github/variables/dev-vars.env
    - name: Generate BUCKET_NAME envvar
      run: echo "BUCKET_NAME=${{env.OWNER}}-terraform-${{env.ENVR}}-state" >> $GITHUB_ENV
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Delete S3 bucket
      run: aws s3 rb s3://${{ env.BUCKET_NAME }} --force
    - if: ${{ inputs.tool == 'terraform' }}
      name: Delete dynamodb table
      run: aws dynamodb delete-table --table-name "${{ env.BUCKET_NAME }}-lock"
...
