name: Build image

on:
  push:
    tags: [ "v[0-9].[0-9]+.[0-9]" ]
    paths:
      - 'app-code/**'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean
      tags:
        description: 'Image tag'
        required: true 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print tags
      if: ${{ inputs.print_tags }}
      run: echo  The tags are ${{ inputs.tags }} 
    - name: Build the Docker image
      run: docker build app-code/ --file app-code/Dockerfile --tag czm41k/weather_checker:${{ inputs.tags }} 
      
## TODO - upload image job
