name: Lint and Scan

on:
  push:
    branches: [ "main" ]
    paths: [ "app-code/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
  scan:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out main
        uses: actions/checkout@main
      - name: Security vulnerabilities scan
        env:
          DEP_PATH: app-code/requirements.txt
        uses: aufdenpunkt/python-safety-check@master
