---
name: Lint and scan python code

on:
  push:
    branches: [ "main" ]
    paths: [ "app-code/**", ".github/workflows/python-ci-check.yml" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out main
        uses: actions/checkout@main
      - name: Install pylint
        run: pip3 install pylint==2.15.2
      - name: List dirs
        run: ls $GITHUB_WORKSPACE/app-code/
      - name: Run linter
        run: pylint $GITHUB_WORKSPACE/app-code/app.py

  scan-bandit:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out main
        uses: actions/checkout@main
      - name: Install bandit
        run: pip3 install bandit==1.7.4
      - name: Run scanner
        run: bandit -r app-code/
...
