---
name: '1-1:Terragrunt CI/CD'
on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/modules/**'
      - '.github/workflows/terragrunt-cicd.yml'
  pull_request:
  # workflow_run:
  #   workflows: ["0-Terraform: Create s3-backend for state"]
  #   types: ["completed"]
  workflow_dispatch:

# env:
#   tf_version: '1.2.9'
#   tg_version: '0.38.12'
#   tf_working_dir: 'terragrunt/dev/eks-infra/'
jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.38.12
      - name: Interact with Terragrunt
        run: terragrunt --version

#     steps:
#       - name: 'Checkout'
#         uses: actions/checkout@master
#       - name: 'Terragrunt Format'
#         uses: the-commons-project/terragrunt-github-actions@master
#         with:
#           tf_actions_version: ${{ env.tf_version }}
#           tg_actions_version: ${{ env.tg_version }}
#           tf_actions_binary: 'terraform'
#           tf_actions_subcommand: 'fmt'
#           tf_actions_working_dir: ${{ env.tf_working_dir }}
#           tf_actions_comment: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terragrunt Init'
#         uses: the-commons-project/terragrunt-github-actions@master
#         with:
#           tf_actions_version: ${{ env.tf_version }}
#           tg_actions_version: ${{ env.tg_version }}
#           tf_actions_subcommand: 'init'
#           tf_actions_working_dir: ${{ env.tf_working_dir }}
#           tf_actions_comment: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terragrunt Validate'
#         uses: the-commons-project/terragrunt-github-actions@master
#         with:
#           tf_actions_version: ${{ env.tf_version }}
#           tg_actions_version: ${{ env.tg_version }}
#           tf_actions_binary: 'terraform'
#           tf_actions_subcommand: 'validate'
#           tf_actions_working_dir: ${{ env.tf_working_dir }}
#           tf_actions_comment: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terragrunt Plan'
#         uses: the-commons-project/terragrunt-github-actions@master
#         with:
#           tf_actions_version: ${{ env.tf_version }}
#           tg_actions_version: ${{ env.tg_version }}
#           tf_actions_subcommand: 'plan'
#           tf_actions_working_dir: ${{ env.tf_working_dir }}
#           tf_actions_comment: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# ...
