---
name: '0-Terraform: Create s3-backend for state'

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/terraform-prepare*'
  workflow_dispatch:

env:
  ENVR: dev
  OWNER: "czm41k"
  AWS_DEFAULT_REGION: "us-west-1"

jobs:
  aws:
    name: 'Run aws-cli'
    runs-on: ubuntu-latest
    steps:
    - name: Generate BUCKET_NAME envvar
      run: echo "BUCKET_NAME=${{env.OWNER}}-terraform-${{env.ENVR}}-state" >> $GITHUB_ENV
    - name: Configure aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Create S3 bucket
      run: aws s3api create-bucket --bucket ${{ env.BUCKET_NAME }} --create-bucket-configuration LocationConstraint=${{ env.AWS_DEFAULT_REGION }}
    - name: Encrypt bucket
      run: |
        aws s3api put-bucket-encryption --bucket ${{ env.BUCKET_NAME }} --server-side-encryption-configuration "{\"Rules\": [{\"ApplyServerSideEncryptionByDefault\":{\"SSEAlgorithm\": \"AES256\"}}]}"
    - name: Create dynamodb table
      run: aws dynamodb create-table --table-name "${{ env.BUCKET_NAME }}-lock" --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
...
