---
name: '1-1:Terragrunt CI/CD'
on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/modules/**'
      - 'terragrunt/**'
      - '.github/workflows/terragrunt-cicd.yml'
  pull_request:
  # workflow_run:
  #   workflows: ["0-Terraform: Create s3-backend for state"]
  #   types: ["completed"]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  terragrunt:
    name: 'Run terragrunt'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terragrunt/dev/eks-infra/
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: ./.github/actions/set-vars
        with:
          varFilePath: ./.github/variables/dev-vars.env
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.38.12
      - name: Interact with Terragrunt
        run: terragrunt --version
      - name: Terragrunt Init
        run: terragrunt init
      - name: Terragrunt plan
        run: terragrunt plan

    # - name: Approve before apply
    #   uses: trstringer/manual-approval@main
    #   with:
    #     secret: ${{ github.TOKEN }}
    #     approvers: ${{ env.OWNER }}
      - name: Terragrunt apply
        run: terragrunt apply -auto-approve
...
